### ISSUE TITLE
Add new accessibility-specific documentation

### ISSUE THREAD

**Issue by steff456** [jupyter/accessibility#125]
## Motivation
This issue will be used to track the documentation writing work about accessibility resources that are scattered over multiple repositories. I know there’s a lot of material that we want to include that goes beyond this list, but I want to start moving the ball of accessibility-specific documentation on the Jupyter project.

## Current status
Right now, the structure of the JupyterLab Accessibility documentation looks like this:

- Home
  - Jupyter accessibility
  - Accessibility docs page
- Accessibility efforts
  - Jupyter Accessibility Statement
- Community
  - Contribute to Jupyter Accessibility
  - Community calls and events
- Accessibility resources
  - Useful Jupyter accessibility resources
  - Mapping JupyterLab’s user interface to source code
- Funded accessibility work
  - Funding accessibility efforts
  - CZI EOSS cycle 4
CZI EOSS cycle 4 - Completed items

## New documentation

- [ ] Notebook authoring guide - as a new page under `accessibility resources` - https://github.com/jupyter/accessibility/pull/127
- [x] Audits - as a new section that will include the audits for 400% zoom and keyboard navigation - https://github.com/jupyter/accessibility/pull/133
  - [x] 400% zoom audit: https://github.com/Quansight-Labs/jupyterlab-accessible-themes/issues/34
  - [x] JupyterLab audit: https://github.com/jupyterlab/jupyterlab/issues/9399
  - [x] Notebook 7 keyboard navigation review: https://github.com/jupyter/notebook/issues/6595
  - [x] Older review describing screen reader compatibility in JupyterLab. https://github.com/jupyterlab/jupyterlab/issues/6573
  - Notebook 7 audit: https://github.com/jupyter/notebook/issues/6800
- [x] WCAG intro and links to resources - as a revamp of the existing page https://jupyter-accessibility.readthedocs.io/en/latest/resources/useful-resources.html - https://github.com/jupyter/accessibility/pull/126/

**Comment by isabela-pf** [comment]
Because it has come up as a request and is something we've built some resources about, I'd like to propose adding 

- [ ] Tips on how to review PRs for accessibility considerations

to our list of new accessibility-specific documentation. I don't think it will be comprehensive, but it can consolidate work that already exists like alt text review tips, keyboard navigation tips, things I know I've commented on PRs when tagged, and some scoped high-stakes WCAG recommendations (ie. the threshold for flashing lights).

Since I'm suggesting this, I'll assign this part to me! I'd also be happy to work on the notebook authoring recommendations and WCAG intro contents, though they'd benefit from the input of others.
