### ISSUE TITLE
Checklinks CI too noisy

### ISSUE THREAD

**Issue by gabalafou** [jupyter/accessibility#139]
Can we remove the checklinks ci or make it optional? We can't control link rot after 3 years

**Comment by gabalafou** [comment]
The failing check is visible on #137

**Comment by krassowski** [comment]
You can ignore specific patterns. Probably better than removing it altogether.

**Comment by gabalafou** [comment]
Idea: log broken links, rather than fail the check?

**Comment by gabalafou** [comment]
check-links action belongs to Jupyter, should be doable to make it a configuration option whether to fail on broken links or just log them

**Comment by tonyfast** [comment]
closing this cause i turned off the ci a bit ago. if a better option comes a long then we should reopen.

**Comment by jtpio** [comment]
For reference I originally added the check links check on CI in https://github.com/jupyter/accessibility/pull/118 because it was not possible to find the meeting notes via the docs site.

Maybe you could narrow done the scope of checked links to still check internal links, and ignore external links if these are not stable enough.

**Comment by tonyfast** [comment]
thanks for the history! if someone spends time reworking the configuration then we should reference this issue in that work.
