### ISSUE TITLE
Create a hosted doc on RTD for meeting minutes and project artifacts

### ISSUE THREAD

**Issue by willingc** [jupyter/accessibility#21]
Create a hosted doc that can be easily searched that combines meeting minutes, writings, explanations, etc.

**Comment by isabela-pf** [comment]
Are you thinking something simple like the [community call notes](https://jupyter.readthedocs.io/en/latest/community/community-call-notes/index.html) but with sections for different topics (like meeting notes versus explanations)?

**Comment by choldgraf** [comment]
I think that the community call notes + some of the sections in the [README](https://github.com/jupyter/accessibility/blob/master/README.md) would be a good start.

Basically, a [team-compass-like](https://jupyterhub-team-compass.readthedocs.io/) documentation structure would be helpful

**Comment by isabela-pf** [comment]
@choldgraf Thanks for sharing! That's a great example I've never seen before.

**Comment by choldgraf** [comment]
The team compass model was first introduced to me by @willingc  - i think it's one of the most useful patterns ever!

**Comment by willingc** [comment]
@isabela-pf I like @choldgraf's suggestion. Let me know if you have any questions.

**Comment by willingc** [comment]
@isabela-pf, I want to introduce you to @sabderemane. I had the chance to chat with Sarah this morning about her interest in contributing to the Python ecosystem and particularly in documentation. She's a Full Stack developer with Git/GitHub experience and an MS in Computer Science. I'm hoping that between you, @trallard, @melisssawm, and myself we can find some ways to get Sarah started with open source contribution. :snake:

**Comment by isabela-pf** [comment]
Hi there @sabderemane! It's lovely to meet you, and welcome to our little corner of the ecosystem!

This issue is for collecting accessibility knowledge around JupyterLab, and I've also been talking to NumPy documentation folks about how we can share knowledge to solve our overlapping problems together. I can think of a lot of different ways that you could explore your interest in documentation, but would it be less overwhelming to meet and talk these out, or to list some ideas in writing? 

Please let me know if there's anything else I can do to help you get started!

(I'm also retagging @melissawm so she gets notified!)

**Comment by sabderemane** [comment]
Hi folks, thank you so much @isabela-pf and @willingc for the introduction 😄 

I'd be happy to contribute to this issue and others projects where I can be helpful. It's my first time create documentation through sphinx, this issue is a good way to learn how to do so. I've got design sensibility and I like improve workflows, automate things if it can help. 

I've start to think to this issue, I write down what I imagine to get everyone following this but I'm available to meet if it's more simple to discuss.

From the previous conversation, I get that the documentation will be structured as well :
- Team information
- Team Guide
- Governance
- Standard Building Blocks

with README informations and community call notes, am I correct ?

Are there any resources I can consult for information to add to the documentation in addition to this repository?

**Comment by isabela-pf** [comment]
I know we spoke elsewhere, but just for public record I'm repeating it. I think this summary sounds correct. I think both the above examples likely use the [PyData Sphinx theme](https://pydata-sphinx-theme.readthedocs.io/en/latest/index.html), so that might be a good place to start (especially since Sphinx will be new to both of us ✨ ). 

As for what content we have, I think we only really have meeting notes and what we could break out of the current readme. Taking the time to write even basic ideas for the other categories you listed will probably be a good exercise, so I'm happy to bring that to the team and get some ideas going in the future.

Let me know if you have any other questions or thoughts, and I'll try and keep this issue updated on any progress!

**Comment by willingc** [comment]
@isabela-pf The PyData Sphinx theme is a good choice. Here's the JupyterHub team compass with the repo with Sphinx: https://github.com/jupyterhub/team-compass/tree/master/docs

I'm happy to answer any Sphinx questions. ReadTheDocs has a very good getting started with Sphinx tutorial: https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html

**Comment by trallard** [comment]
Samesies - I am happy to help with any Sphinx /  RTD questions.  We can always sort a team-programming session to get things rolling

**Comment by sabderemane** [comment]
I've done a draft PR, happy to get feedbacks if you have one !
I also hosted a preview for people to follow up what's already done easily : https://sa-docs-test.readthedocs.io/en/latest/

Governance and Standard Building Blocks has no content yet, if you have any suggestion for that, please let me know.

As we discussed with @isabela-pf, I was thinking of a contribution guide to the project, should I create an issue for that ?

**Comment by isabela-pf** [comment]
I just merged #46 which addresses this issue. I'm not closing this yet since there is still some discussion here we may want to include in iterating on this. 

> As we discussed with @isabela-pf, I was thinking of a contribution guide to the project, should I create an issue for that ?
That sounds good to me! I think we haven't had one yet since this repo is more of a storage for knowledge than producing a single piece of software, but it sounds like a good idea since people are definitely still contributing knowledge.

**Comment by isabela-pf** [comment]
@sabderemane did a great job with #46, so I'm following up on what I think is left to close this issue!
- [ ] Set up hosting for the docs
- [ ] Link the docs in the readme and repo's about.

**Comment by sabderemane** [comment]
> I'm not closing this yet since there is still some discussion here we may want to include in iterating on this.
I've created #47 for that to separate the discussion of the hosted documentation

I can't do this since I'm not a jupyter member of the organization, but if I can help for anything help, feel free to ask!

**Comment by blink1073** [comment]
I created the RTD project and added `willingc` as a maintainer.  @isabela-pf  do you have a RTD account?  `isabela-pf` was not a valid user.

**Comment by isabela-pf** [comment]
@blink1073 I don't have an RTD account, but if it's wanted I can set one up!

**Comment by blink1073** [comment]
Only if you want one :smile:

**Comment by tonyfast** [comment]
@blink1073 is there anyway you could link my rtd account so i can start getting the docs hosting setup?

**Comment by blink1073** [comment]
I added `tonyfast`, is that correct?

**Comment by tonyfast** [comment]
indeed. thanks bro.

**Comment by blink1073** [comment]
👊🏼

**Comment by trallard** [comment]
This seems to have been sorted so will close - and can reopen if anyone thinks this needs keeping alive
